evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,true).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,true).
evidence(cancer,true).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,true).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,true).
evidence(cancer,true).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,true).
evidence(xray_abnormal,true).
evidence(tb_or_ca,true).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,true).
evidence(cancer,true).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,true).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,true).
evidence(tb_or_ca,true).
evidence(cancer,true).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,true).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,true).
evidence(bronchitis,true).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,false).
---
evidence(tuberculosis,false).
evidence(xray_abnormal,false).
evidence(tb_or_ca,false).
evidence(cancer,false).
evidence(dyspnea,false).
evidence(bronchitis,false).
evidence(travel,false).
evidence(smoker,true).
